/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package training.model;

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;

@Entity
@NamedQuery(query = "SELECT lb FROM Library lb WHERE lb.id = :id", name = "findLibraryById")
public class Library {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int id;
	private String name;
	@OneToOne
	private Student student;
	@ManyToMany(targetEntity = Student.class)
	private List<Student> stud;

	public Library() {
		super();
	}

	public Library(int id, String name, Student student, List<Student> stud) {
		super();
		this.id = id;
		this.name = name;
		this.student = student;
		this.stud = stud;
	}

	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}

	/**
	 * @param id
	 *          the id to set
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name
	 *          the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the student
	 */
	public Student getStudent() {
		return student;
	}

	/**
	 * @param student
	 *          the student to set
	 */
	public void setStudent(Student student) {
		this.student = student;
	}

	/**
	 * @return the stud
	 */
	public List<Student> getStud() {
		return stud;
	}

	/**
	 * @param stud
	 *          the stud to set
	 */
	public void setStud(List<Student> stud) {
		this.stud = stud;
	}

}
